# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'haleditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HalEditor(object):
    def setupUi(self, HalEditor):
        HalEditor.setObjectName("HalEditor")
        HalEditor.resize(1253, 799)
        HalEditor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        HalEditor.setStyleSheet("QTreeView {\n"
"    border-radius: 10px;\n"
"    background:white;\n"
"    color: #333333;\n"
"}\n"
"QTreeView::item {\n"
"    height: 30px;\n"
"    border-radius: 5px;\n"
"}\n"
"QTreeView::item:selected {\n"
"    color:black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(HalEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setMinimumSize(QtCore.QSize(500, 0))
        self.graphicsView.setStyleSheet("border-radius: 10px;\n"
"background: white;\n"
"border: 1px solid lightgrey;")
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeView.setStyleSheet("border: 1px solid lightgrey;")
        self.treeView.setAutoScroll(True)
        self.treeView.setDragEnabled(True)
        self.treeView.setRootIsDecorated(True)
        self.treeView.setSortingEnabled(False)
        self.treeView.setAnimated(True)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(True)
        self.gridLayout.addWidget(self.treeView, 0, 0, 1, 1)
        HalEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HalEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1253, 20))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        HalEditor.setMenuBar(self.menubar)
        self.action_2 = QtWidgets.QAction(HalEditor)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(HalEditor)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(HalEditor)
        self.action_4.setObjectName("action_4")
        self.action_6 = QtWidgets.QAction(HalEditor)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(HalEditor)
        self.action_7.setObjectName("action_7")
        self.action_9 = QtWidgets.QAction(HalEditor)
        self.action_9.setObjectName("action_9")
        self.menu.addSeparator()
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action_4)
        self.menu.addSeparator()
        self.menu.addAction(self.action_6)
        self.menu.addAction(self.action_7)
        self.menu.addSeparator()
        self.menu.addAction(self.action_9)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(HalEditor)
        QtCore.QMetaObject.connectSlotsByName(HalEditor)

    def retranslateUi(self, HalEditor):
        _translate = QtCore.QCoreApplication.translate
        HalEditor.setWindowTitle(_translate("HalEditor", "Hal Editor"))
        self.menu.setTitle(_translate("HalEditor", "Файл"))
        self.menu_2.setTitle(_translate("HalEditor", "О программе"))
        self.action_2.setText(_translate("HalEditor", "Новый"))
        self.action_3.setText(_translate("HalEditor", "Открыть"))
        self.action_4.setText(_translate("HalEditor", "Последние"))
        self.action_6.setText(_translate("HalEditor", "Сохранить"))
        self.action_7.setText(_translate("HalEditor", "Сохранить как"))
        self.action_9.setText(_translate("HalEditor", "Выход"))
